name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
# PEARL: The VersionPrefix, VersionSuffix mechanism is retarded, because:
#        - The version prefix must be exactly three numbers separated by periods. 
#          If you omit the last number, a zero will be automagically supplied for you.
#        - Apparently, the entire version number may contain at most one dash, which is automagically supplied when the
#          version-prefix is concatenated with the version-suffix, so the version suffix itself may not contain a dash. 
#          If it does, you get: "The package manifest contains an invalid Version: '1.0.0-9-1'"
#        - And, to top it all off, the suffix does not actually change the version of the package; instead, it causes 
#          nuget to treat the version as a pre-release version.  
#          This is a misapplication of abstraction: the "VersionSuffix" is not some general-purpose suffix for the 
#          version, it is a "Pre-release version specifier", which happens to be used as a suffix.
#          The result of all this is that the whole prefix-suffix mechanism serves a very narrowly scoped purpose and
#          is entirely useless for any other scenario.
#        Therefore, we have to specify the entire version here.
  RELEASE_VERSION: 1.1.${{github.run_number}}.${{github.run_attempt}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: "restore"
      run: dotnet restore

    - name: "build: Debug"
      run: dotnet build --configuration Debug --no-restore --verbosity detailed

    - name: "test"
      run: dotnet test --configuration Debug --no-build --verbosity normal

    - name: "build: Release"
      run: dotnet build --configuration Release --no-restore

    - name: "pack"
      run: dotnet pack --configuration Release --no-restore --no-build

    - name: "print stuff"
      run: echo ${{ github.event.repository.name }} - ${GITHUB_REPOSITORY#*/} - ${{ github.run_number }} - ${{ github.run_attempt }}

    - name: "push"
      run: dotnet nuget push "MikeNakis.Kit/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
